[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
presence = "CFZsFPtvwo5KDenV3qgorroaRmT7NuYsfPnd4avFS2cT"

[programs.devnet]
presence = "CFZsFPtvwo5KDenV3qgorroaRmT7NuYsfPnd4avFS2cT"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p presence-tests -- --test-threads=1"
